name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  - name: buildConfiguration
    value: 'Release'
  - name: keyVaultName
    value: 'rgvault254' # Your Key Vault name
  - name: targetDirectory
    value: 'C:\Apps\key-vault-app' # On-premise deployment path

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md

stages:
- stage: Build
  displayName: 'Build & Test'
  jobs:
  - job: Build
    displayName: 'Build Application'
    pool:
      name: 'onprem-server-01'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET 9.0 SDK'
      inputs:
        packageType: 'sdk'
        version: '9.0.x'

    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet Packages'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build Solution'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish Artifacts'
      inputs:
        command: 'publish'
        projects: '**/key-vault-dotnet-core-quickstart.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        publishWebProjects: false

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Build Artifacts'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: 'Deploy to On-Premise'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: 'Deploy Application'
    pool:
      name: 'onprem-server-01'
    steps:
    - download: current
      artifact: 'drop'
      displayName: 'Download Build Artifacts'

    - task: AzureKeyVault@2
      displayName: 'Fetch Key Vault Secrets'
      inputs:
        azureSubscription: 'Azure-Connection-Name'
        KeyVaultName: '$(keyVaultName)'
        SecretsFilter: 'AppSecret'
        RunAsPreJob: false

    - task: PowerShell@2
      displayName: 'Deploy to On-Premise Server'
      inputs:
        targetType: 'filePath'
        filePath: '$(Pipeline.Workspace)/drop/deploy.ps1'
        arguments: > 
          -TargetDir '$(targetDirectory)' 
          -SecretValue '$(AppSecret)'
        pwsh: true